---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: "100%"
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      serviceAccountName: manager
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: odh-notebook-controller-image_PLACEHOLDER
          imagePullPolicy: Always
          command:
            - /manager
          args: ["--oauth-proxy-image", "registry.redhat.io/openshift4/ose-oauth-proxy@sha256:4f8d66597feeb32bb18699326029f9a71a5aca4a57679d636b876377c2e95695"]
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 256Mi
          env:
            - name: SET_PIPELINE_RBAC
              value: "true"
            - name: SET_PIPELINE_SECRET
              value: "true"
