---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: rhods-operator
    role: recording-rules
  name: rhods-prometheus-alerting-operator
  namespace: redhat-ods-monitoring
spec:
  groups:
  - name: SLOs - RHODS Operator v2
    interval: 15m  # overwrite global.evaluation_interval 10s
    rules:
    - expr: |
        rate(controller_runtime_reconcile_total{controller="rhods-controller", job="RHODS Metrics", result!="success"}[15m])
      labels:
        instance: rhods-controller
      record: controller_runtime_reconcile_total:rate15m
